version: '3.9'
services:
  db:
    image: postgres:13
    volumes:
      - carniviews-django_postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: carniviews
      POSTGRES_USER: carniviews_user
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "-U postgres"
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: carniviews_django.settings
      DB_NAME: carniviews
      DB_USER: carniviews_user
      DB_PASSWORD: secret
      DB_HOST: db

volumes:
  carniviews-django_postgres_data: