# Generated by Django 4.2.19 on 2025-05-10 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsuggestion',
            name='content_type_label',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
