# Generated by Django 4.2.19 on 2025-04-13 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_unverifiedcompany'),
        ('images_app', '0002_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='company',
        ),
        migrations.AddField(
            model_name='image',
            name='unverified_company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company_app.unverifiedcompany'),
            preserve_default=False,
        ),
    ]
