# Generated by Django 4.2.19 on 2025-04-16 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_alter_unverifiedcompany_address_and_more'),
        ('images_app', '0004_alter_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='unverified_company',
        ),
        migrations.AddField(
            model_name='image',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company_app.company'),
            preserve_default=False,
        ),
    ]
