# Generated by Django 4.2.19 on 2025-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hours',
            field=models.JSONField(default=dict),
        ),
    ]
