# Generated by Django 4.2.19 on 2025-04-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_event_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hours',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
