# Generated by Django 4.2.19 on 2025-04-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.CharField(default=1, max_length=1255),
            preserve_default=False,
        ),
    ]
