# Generated by Django 4.2.19 on 2025-04-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_alter_eventimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
