# Generated by Django 4.2.19 on 2025-04-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_alter_eventimage_image'),
    ]

    operations = [
    ]
