# Generated by Django 4.2.19 on 2025-04-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_auto_20250414_0934'),
    ]

    operations = [
    ]
