# Generated by Django 4.2.19 on 2025-04-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_auto_20250414_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
