# Generated by Django 4.2.19 on 2025-04-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0010_event_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='event',
            name='state',
        ),
        migrations.RemoveField(
            model_name='event',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='event',
            name='address_line1',
            field=models.CharField(default='', max_length=1255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='address_line2',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Zip Code, Postal Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, help_text='State, Province, Region, Parish, etc.', max_length=100, null=True),
        ),
    ]
