# Generated by Django 4.2.19 on 2025-05-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0013_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photos',
            field=models.JSONField(default=dict),
        ),
    ]
