# Generated by Django 4.2.19 on 2025-05-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0014_event_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='claps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
