# Generated by Django 4.2.19 on 2025-05-30 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1255)),
                ('address_line1', models.CharField(max_length=1255)),
                ('address_line2', models.CharField(blank=True, max_length=1255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, help_text='State, Province, Region, Parish, etc.', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Zip Code, Postal Code', max_length=20, null=True)),
                ('claps', models.IntegerField(blank=True, default=0, null=True)),
                ('country', models.CharField(max_length=100)),
                ('hours', models.CharField(blank=True, max_length=255, null=True)),
                ('company_type', models.CharField(max_length=100)),
                ('photos', models.JSONField(default=dict)),
                ('hoursData', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unverified_business_app_user', to='user_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1255)),
                ('address_line1', models.CharField(max_length=1255)),
                ('address_line2', models.CharField(blank=True, max_length=1255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, help_text='State, Province, Region, Parish, etc.', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Zip Code, Postal Code', max_length=20, null=True)),
                ('claps', models.IntegerField(blank=True, default=0, null=True)),
                ('country', models.CharField(max_length=100)),
                ('hours', models.CharField(blank=True, max_length=255, null=True)),
                ('company_type', models.CharField(max_length=100)),
                ('photos', models.JSONField(default=dict)),
                ('hoursData', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_business_app_user', to='user_app.customuser')),
            ],
        ),
    ]
