# Generated by Django 4.2.19 on 2025-04-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0002_unverifiedbusiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverifiedbusiness',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='unverifiedbusiness',
            name='hoursData',
        ),
        migrations.RemoveField(
            model_name='unverifiedbusiness',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='unverifiedbusiness',
            name='website',
        ),
    ]
