# Generated by Django 4.2.19 on 2025-04-29 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0003_remove_unverifiedbusiness_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifiedbusiness',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unverifiedbusiness',
            name='hoursData',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='unverifiedbusiness',
            name='photos',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='unverifiedbusiness',
            name='website',
            field=models.URLField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
