# Generated by Django 4.2.19 on 2025-05-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0005_remove_business_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='claps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unverifiedbusiness',
            name='claps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
