# Generated by Django 4.2.19 on 2025-05-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0007_alter_unverifiedbusiness_claps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='claps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
