# Generated by Django 4.2.19 on 2025-03-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyInfo', models.TextField(default='{}')),
                ('companyImages', models.TextField(default='[]')),
                ('hoursData', models.TextField(default='{}')),
            ],
        ),
    ]
