# Generated by Django 4.2.19 on 2025-03-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('hours', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=100)),
                ('photos', models.JSONField(default=list)),
                ('hoursData', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
