# Generated by Django 4.2.19 on 2025-03-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyImages',
        ),
    ]
