# Generated by Django 4.2.19 on 2025-04-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('company_app', '0004_auto_20250408_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('hours', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=100)),
                ('photos', models.JSONField(default=list)),
                ('hoursData', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unverified_companies', to='user_app.customuser')),
            ],
        ),
    ]
