# Generated by Django 4.2.19 on 2025-04-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_alter_unverifiedcompany_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unverifiedcompany',
            old_name='address',
            new_name='address_line1',
        ),
        migrations.RemoveField(
            model_name='unverifiedcompany',
            name='state',
        ),
        migrations.RemoveField(
            model_name='unverifiedcompany',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='address_line2',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Zip Code, Postal Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='region',
            field=models.CharField(blank=True, help_text='State, Province, Region, Parish, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unverifiedcompany',
            name='hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
