# Generated by Django 4.2.19 on 2025-04-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0008_remove_company_address_remove_company_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-18T19:58:00Z'),
            preserve_default=False,
        ),
    ]
