# Generated by Django 4.2.19 on 2025-04-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0009_company_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
