# Generated by Django 4.2.19 on 2025-04-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0010_company_contact_unverifiedcompany_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='website',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
