# Generated by Django 4.2.19 on 2025-04-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0012_recommendation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='band_app',
        ),
        migrations.AlterModelTable(
            name='unverifiedcompany',
            table='unverifiedband_app',
        ),
    ]
