# Generated by Django 4.2.19 on 2025-04-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0014_alter_recommendation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='normalized_country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='normalized_country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
