# Generated by Django 4.2.19 on 2025-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0015_company_normalized_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='socials',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='socials',
            field=models.JSONField(default=dict),
        ),
    ]
