# Generated by Django 4.2.19 on 2025-04-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0017_alter_company_socials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='socials',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='unverifiedcompany',
            name='socials',
            field=models.JSONField(default=dict),
        ),
    ]
