# Generated by Django 4.2.19 on 2025-05-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0018_alter_company_socials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='claps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='claps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
