# Generated by Django 4.2.19 on 2025-05-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0020_alter_unverifiedcompany_claps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='claps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
