# Generated by Django 4.2.19 on 2025-05-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0021_alter_company_claps'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bandStories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='bandStories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
