# Generated by Django 4.2.19 on 2025-05-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0022_company_bandstories_unverifiedcompany_bandstories'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='overall_avg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='unverifiedcompany',
            name='overall_avg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
