# Generated by Django 4.2.19 on 2025-03-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='family_name',
            new_name='familyName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='given_name',
            new_name='givenName',
        ),
    ]
