# Generated by Django 4.2.19 on 2025-05-13 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('company_app', '0018_alter_company_socials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intro', models.TextField(blank=True, null=True)),
                ('vibe', models.TextField(blank=True, null=True)),
                ('costume', models.TextField(blank=True, null=True)),
                ('moments', models.TextField(blank=True, null=True)),
                ('reflection', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_stories', to='company_app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_stories', to='user_app.customuser')),
            ],
        ),
    ]
