# Generated by Django 4.2.19 on 2025-04-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('company_app', '0012_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('submitted_by', models.TextField()),
                ('music', models.FloatField(default=0.0, null=True)),
                ('service', models.FloatField(default=0.0, null=True)),
                ('vibes', models.FloatField(default=0.0, null=True)),
                ('costume', models.FloatField(default=0.0, null=True)),
                ('price', models.FloatField(default=0.0, null=True)),
                ('food', models.FloatField(default=0.0, null=True)),
                ('value', models.FloatField(default=0.0, null=True)),
                ('amenities', models.FloatField(default=0.0, null=True)),
                ('pickup', models.FloatField(default=0.0, null=True)),
                ('rating', models.JSONField(blank=True, default=list, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='company_app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user_app.customuser')),
            ],
        ),
    ]
