# Generated by Django 4.2.19 on 2025-04-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
