# Generated by Django 5.1.5 on 2025-03-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_review_delete_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
