# Generated by Django 4.2.19 on 2025-04-23 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0003_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='submitted_by',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
