# Generated by Django 4.2.19 on 2025-04-28 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('review_app', '0004_remove_review_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.CharField(max_length=255)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review_app.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_users', to='user_app.customuser')),
            ],
            options={
                'db_table': 'review_agreement',
            },
        ),
    ]
