# Generated by Django 4.2.19 on 2025-04-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0004_review_review_date_review_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='amenities',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='costume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='food',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='music',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='pickup',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='vibes',
            field=models.FloatField(default=0.0),
        ),
    ]
