# Generated by Django 4.2.19 on 2025-05-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0005_revagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='overall',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
