# Generated by Django 4.2.19 on 2025-04-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feeback',
            new_name='feedback',
        ),
    ]
